"""
app/rag/agents/planner.py

Query Planning Agent — decides retrieval strategy before each attempt.

Determines:
  - which Supabase source type to target (grade/course/requirement/instructor)
  - vector vs keyword weight (alpha)
  - how to reformulate the query on retries

Rule-based (no LLM calls) to keep it fast. The query_rewriter handles
LLM-based query optimization separately; the planner handles strategy.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field

logger = logging.getLogger("darvis.agents.planner")

# Ordered most-specific → least-specific so earlier rules win
_SOURCE_RULES: list[tuple[str, str]] = [
    ("requirement", r"\b(require|requirement|degree|major|graduate|graduation|need for|needed|fulfill|curriculum|what courses do i need)\b"),
    ("instructor",  r"\b(rating|rmp|rate my professor|review|reputation)\b"),
    ("grade",       r"\b(gpa|grade|f rate|a rate|fail|pass|withdraw|professor|instructor|teach|prof|hardest|easiest|brutal|tough|avoid|outcomes)\b"),
    ("course",      r"\b(course|class|description|credits?|prereq|prerequisite|offered|syllabus|about the class|what is)\b"),
]

_COURSE_CODE_RE = re.compile(r"\b([A-Z]{2,4})\s*(\d{4})\b")
_SEMANTIC_BOOST_RE = re.compile(r"\b(best|worst|hardest|easiest|recommend|brutal|tough|safe|risky)\b", re.I)
_EXACT_ID_RE = re.compile(r"\b[A-Z]{2,4}\s*\d{4}\b")
_PROF_HINT_RE = re.compile(r"\b(?:prof(?:essor)?|instructor|teacher)\s+([A-Z][a-z]+)\b", re.I)


@dataclass
class QueryPlan:
    primary_query: str
    source_filter: str | None = None   # "grade" | "course" | "requirement" | "instructor" | None
    alpha: float = 0.7                 # 1.0 = pure semantic, 0.0 = pure keyword
    intent_type: str = "general"
    mentioned_course: str | None = None
    mentioned_instructor: str | None = None
    # Semantically varied alternatives generated by replan() for retry attempts.
    # AgenticRAGPipeline uses primary_query on each attempt (set by replan).
    query_variants: list[str] = field(default_factory=list)


class QueryPlannerAgent:
    """Produces a retrieval plan from the raw user question. No LLM — always fast."""

    def plan(self, question: str) -> QueryPlan:
        q_upper = question.upper()
        q_lower = question.lower()

        source_filter = self._detect_source_filter(q_lower)
        # Course codes in original case for pattern matching
        if source_filter == "grade" or (source_filter is None and _EXACT_ID_RE.search(q_upper)):
            source_filter = "grade"

        alpha = self._detect_alpha(q_lower, q_upper)
        mentioned_course = self._extract_course(q_upper)
        mentioned_instructor = self._extract_instructor(question)

        plan = QueryPlan(
            primary_query=question,
            source_filter=source_filter,
            alpha=alpha,
            intent_type=source_filter or "general",
            mentioned_course=mentioned_course,
            mentioned_instructor=mentioned_instructor,
        )
        logger.info(
            "[planner] plan source=%s alpha=%.2f course=%s instr=%s",
            plan.source_filter, plan.alpha, plan.mentioned_course, plan.mentioned_instructor,
        )
        return plan

    def replan(self, question: str, prev_plan: QueryPlan, attempt: int) -> QueryPlan:
        """
        Generate a semantically varied retrieval strategy for retry attempts.

        attempt=1: entity-focused query (course code + instructor + metric keywords)
        attempt=2: topic-expanded query (nickname + broad metric terms, no filter)

        primary_query is set to the variant so AgenticRAGPipeline passes it to
        retrieve_full() instead of the raw user question.
        """
        variants = self._build_variants(question, prev_plan)

        if attempt == 1:
            primary = variants[0] if variants else question
            new_plan = QueryPlan(
                primary_query=primary,
                source_filter=None,           # broaden: drop source restriction
                alpha=max(0.4, prev_plan.alpha - 0.2),
                intent_type=prev_plan.intent_type + "_r1",
                mentioned_course=prev_plan.mentioned_course,
                mentioned_instructor=prev_plan.mentioned_instructor,
                query_variants=variants,
            )
        else:
            primary = variants[1] if len(variants) > 1 else (variants[0] if variants else question)
            new_plan = QueryPlan(
                primary_query=primary,
                source_filter=None,
                alpha=0.2,                    # keyword-dominant on last attempt
                intent_type=prev_plan.intent_type + "_r2",
                mentioned_course=prev_plan.mentioned_course,
                mentioned_instructor=prev_plan.mentioned_instructor,
                query_variants=variants,
            )

        logger.info(
            "[planner] replan attempt=%d source=%s alpha=%.2f query=%r",
            attempt, new_plan.source_filter, new_plan.alpha, new_plan.primary_query[:60],
        )
        return new_plan

    def _build_variants(self, question: str, plan: QueryPlan) -> list[str]:
        """
        Build up to 2 semantically varied query strings from the plan's extracted entities.

        Variant 0 (attempt 1) — entity-focused: course code + instructor + metric keywords.
          "which CS 3114 prof is hardest" → "CS 3114 grade GPA F rate fail Hamouda"
        Variant 1 (attempt 2) — topic-expanded: nickname synonyms + broad metric terms.
          "which CS 3114 prof is hardest" → "algorithms data structures grade difficulty F rate"
        """
        parts_entity: list[str] = []
        parts_topic: list[str] = []

        if plan.mentioned_course:
            parts_entity.append(plan.mentioned_course)
            # Map course code to topic synonyms for variant 1
            _COURSE_TOPICS = {
                "CS 3114": "algorithms data structures",
                "CS 2114": "data structures",
                "CS 3214": "systems software",
                "CS 3704": "software engineering design",
                "CS 2506": "computer organization assembly",
                "CS 4264": "computer networks",
                "CS 4205": "compiler construction",
                "CS 3204": "operating systems",
                "CS 2505": "discrete mathematics",
                "CS 4824": "machine learning",
                "CS 4804": "artificial intelligence",
                "CS 4604": "database management",
            }
            topic = _COURSE_TOPICS.get(plan.mentioned_course, "")
            if topic:
                parts_topic.append(topic)
            else:
                parts_topic.append(plan.mentioned_course)

        if plan.mentioned_instructor:
            parts_entity.append(plan.mentioned_instructor)

        # Infer metric keywords from the original question
        q_lower = question.lower()
        if any(w in q_lower for w in ("hard", "brutal", "tough", "avoid", "fail", "worst")):
            parts_entity.append("grade F rate fail low GPA difficulty")
            parts_topic.append("F rate fail difficulty low GPA")
        elif any(w in q_lower for w in ("easy", "best", "pass", "safe", "high gpa")):
            parts_entity.append("grade high GPA A rate pass")
            parts_topic.append("high GPA A rate pass")
        else:
            parts_entity.append("grade GPA A rate")
            parts_topic.append("grade GPA outcomes")

        variant_entity = " ".join(parts_entity) if parts_entity else question
        variant_topic = " ".join(parts_topic) if parts_topic else question

        # Deduplicate
        variants = []
        if variant_entity != question:
            variants.append(variant_entity)
        if variant_topic != question and variant_topic != variant_entity:
            variants.append(variant_topic)

        return variants

    # ── Helpers ────────────────────────────────────────────────────────────────

    def _detect_source_filter(self, q_lower: str) -> str | None:
        for source, pattern in _SOURCE_RULES:
            if re.search(pattern, q_lower):
                return source
        return None

    def _detect_alpha(self, q_lower: str, q_upper: str) -> float:
        if _EXACT_ID_RE.search(q_upper):
            return 0.6  # exact course code → give keywords more weight
        if _SEMANTIC_BOOST_RE.search(q_lower):
            return 0.8  # vague semantic intent → lean on vectors
        return 0.7

    def _extract_course(self, q_upper: str) -> str | None:
        m = _COURSE_CODE_RE.search(q_upper)
        return f"{m.group(1)} {m.group(2)}" if m else None

    def _extract_instructor(self, question: str) -> str | None:
        m = _PROF_HINT_RE.search(question)
        return m.group(1) if m else None
